### ISSUE TITLE
Link all pages

### ISSUE THREAD

**Issue by VinhVTHE181750** [VinhVTHE181750/mJOB#169]
### **DATABASE**
- [x] Auth
- [x] User
- [x] Forum
- [x] Jobs
- [ ] Metrics
- [ ] Payment

### **TEST RUN**
To /home
- [ ] Forum
- [x] Jobs
- [ ] Payment
- [x] Profile
- [x] Admin dashboard
- [ ] Auth

To pages in the same feature
- [ ] Home
- [x] Forum
- [x] Jobs
- [ ] Payment
- [x] Profile
- [x] Admin dashboard
- [ ] Auth

Test on one PC:
- [ ] Home
- [x] Forum
- [ ] Jobs
- [ ] Payment
- [x] Profile
- [x] Admin dashboard
- [ ] Auth

**Comment by HE176788MaiNhatHoang** [comment]
has seen and will update daily
